# Test dello scaricamento dei dati MU dal portale cantonale.
#
# NIENTE RETE: l'indice si legge da un campione salvato e gli archivi si
# costruiscono al volo. Un test che chiama data.geo.ti.ch fallirebbe in aereo,
# sarebbe lento, e soprattutto non proverebbe nulla che non provi gia' il
# campione - mentre le cose che possono davvero rompersi (formato della pagina,
# nomi pericolosi nell'archivio, impronta che non torna) qui si provano tutte.
#
# Eseguire con l'interprete di QGIS o con python normale:
#   python test_scarica_mu.py
import hashlib
import io
import os
import sys
import tempfile
import unittest
import zipfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tidashboard import scarica_mu as S

# Due righe della tabella vera, copiate dal portale il 16.08.2026 (con le
# stesse classi CSS e lo stesso annidamento).
PAGINA = """
<table class="table">
<tr>
  <td width="30%"><a href="?p=ti_mu_version1_7_mn95&f=5304000101.zip">5304000101.zip</a></td>
  <td width="30%">Bosco Gurin</td>
  <td width="20%">30.07.2026</td>
  <td width="20%">904.63 KB</td>
</tr>
<tr>
  <td width="30%"><a href="?p=ti_mu_version1_7_mn95&f=5254010100.zip">5254010100.zip</a></td>
  <td width="30%">Mendrisio</td>
  <td width="20%">14.08.2026</td>
  <td width="20%">11.21 MB</td>
</tr>
<tr>
  <td width="30%"><a href="?p=ti_mu_version1_7_mn95&f=5003990301.zip">5003990301.zip</a></td>
  <td width="30%">Cadenazzo/Monteceneri (comunanza)</td>
  <td width="20%">29.05.2026</td>
  <td width="20%">306.55 KB</td>
</tr>
</table>
"""

ITF = (b"SCNT\r\n"
       b"INTERLIS Export generated by Autodesk Industry Model\r\n"
       b"////\r\n"
       b"MTID INTERLIS1\r\n"
       b"MODL MD01MUTI7MN95\r\n"
       b"TOPI Punti_fissiCategoria1\r\n")


def _archivio(cartella, nome_itf="5304000101.itf", contenuto=ITF, md5=True,
              nomi_extra=()):
    percorso = os.path.join(cartella, "prova.zip")
    with zipfile.ZipFile(percorso, "w") as z:
        z.writestr(nome_itf, contenuto)
        if md5:
            impronta = hashlib.md5(contenuto).hexdigest().upper()
            z.writestr(nome_itf + ".md5", impronta)
        for n in nomi_extra:
            z.writestr(n, b"x")
    return percorso


class TestIndice(unittest.TestCase):
    def test_legge_le_righe_della_tabella(self):
        comuni = S.leggi_indice(PAGINA)
        self.assertEqual(len(comuni), 3)
        primo = comuni[0]
        self.assertEqual(primo.archivio, "5304000101.zip")
        self.assertEqual(primo.nome, "Bosco Gurin")
        self.assertEqual(primo.data, "30.07.2026")
        self.assertEqual(primo.dimensione, "904.63 KB")

    def test_codice_e_url(self):
        primo = S.leggi_indice(PAGINA)[0]
        self.assertEqual(primo.codice, "5304000101")
        self.assertEqual(
            primo.url,
            "https://data.geo.ti.ch/geodata/ti_mu_version1_7_mn95/5304000101.zip")

    def test_i_nomi_con_la_barra_restano_interi(self):
        """Le comunanze hanno un nome con la barra e le parentesi: e' il caso
        che una pulizia troppo zelante taglierebbe."""
        nomi = [c.nome for c in S.leggi_indice(PAGINA)]
        self.assertIn("Cadenazzo/Monteceneri (comunanza)", nomi)

    def test_una_pagina_vuota_non_esplode(self):
        self.assertEqual(S.leggi_indice(""), [])
        self.assertEqual(S.leggi_indice(None), [])
        self.assertEqual(S.leggi_indice("<html><body>manutenzione</body></html>"), [])

    def test_la_stessa_riga_ripetuta_conta_una_volta(self):
        comuni = S.leggi_indice(PAGINA + PAGINA)
        self.assertEqual(len(comuni), 3)


class TestEstrazione(unittest.TestCase):
    def test_estrae_l_itf_e_verifica_l_impronta(self):
        cartella = tempfile.mkdtemp()
        percorso = _archivio(cartella)
        righe = []
        itf = S.estrai_itf(percorso, cartella, log=righe.append)
        self.assertTrue(os.path.exists(itf))
        with io.open(itf, "rb") as f:
            self.assertEqual(f.read(), ITF)
        self.assertTrue(any("MD5" in r for r in righe))

    def test_un_itf_manomesso_viene_respinto_e_cancellato(self):
        """E' il caso vero: connessione caduta a meta'. Un ITF troncato e' per
        tutto il resto della catena indistinguibile da uno buono, finche'
        ili2gpkg non fallisce parlando d'altro."""
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "rotto.zip")
        with zipfile.ZipFile(percorso, "w") as z:
            z.writestr("x.itf", ITF[:20])
            z.writestr("x.itf.md5", hashlib.md5(ITF).hexdigest().upper())
        with self.assertRaises(S.ArchivioNonValido) as e:
            S.estrai_itf(percorso, cartella)
        self.assertIn("impronta", str(e.exception))
        self.assertFalse(os.path.exists(os.path.join(cartella, "x.itf")),
                         "un ITF che non passa il controllo non deve restare li'")

    def test_senza_file_md5_estrae_lo_stesso_ma_avvisa(self):
        cartella = tempfile.mkdtemp()
        percorso = _archivio(cartella, md5=False)
        righe = []
        itf = S.estrai_itf(percorso, cartella, log=righe.append)
        self.assertTrue(os.path.exists(itf))
        self.assertTrue(any("non verificata" in r for r in righe))

    def test_archivio_senza_itf(self):
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "vuoto.zip")
        with zipfile.ZipFile(percorso, "w") as z:
            z.writestr("leggimi.txt", b"niente")
        with self.assertRaises(S.ArchivioNonValido):
            S.estrai_itf(percorso, cartella)

    def test_un_nome_che_esce_dalla_cartella_viene_rifiutato(self):
        """Zip Slip: un archivio puo' contenere '../../qualcosa' e scrivere
        dove gli pare. Il file arriva da un portale pubblico su HTTPS, ma
        fidarsi della provenienza non e' un controllo."""
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "cattivo.zip")
        with zipfile.ZipFile(percorso, "w") as z:
            z.writestr("../../fuori.itf", ITF)
        with self.assertRaises(S.ArchivioNonValido):
            S.estrai_itf(percorso, cartella)
        self.assertFalse(os.path.exists(
            os.path.join(os.path.dirname(os.path.dirname(cartella)), "fuori.itf")))

    def test_nome_sicuro(self):
        self.assertEqual(S._nome_sicuro("a/b/c.itf"), "c.itf")
        self.assertEqual(S._nome_sicuro("a\\b\\c.itf"), "c.itf")
        for cattivo in ("..", "a/..", "C:evil.itf", "", "dir/"):
            with self.assertRaises(S.ArchivioNonValido):
                S._nome_sicuro(cattivo)


class TestModello(unittest.TestCase):
    def test_legge_la_riga_modl(self):
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "x.itf")
        with io.open(percorso, "wb") as f:
            f.write(ITF)
        self.assertEqual(S.modello_dichiarato(percorso), "MD01MUTI7MN95")
        self.assertEqual(S.modello_dichiarato(percorso), S.MODELLO_ATTESO)

    def test_modello_federale_riconosciuto_come_diverso(self):
        """Il caso che ha fatto nascere questo modulo: geodienste.ch pubblica
        lo stesso tema in un modello che il plugin non sa leggere."""
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "y.itf")
        with io.open(percorso, "wb") as f:
            f.write(ITF.replace(b"MD01MUTI7MN95", b"MD01MUCH24MN95I"))
        self.assertEqual(S.modello_dichiarato(percorso), "MD01MUCH24MN95I")
        self.assertNotEqual(S.modello_dichiarato(percorso), S.MODELLO_ATTESO)

    def test_file_che_non_c_e(self):
        self.assertEqual(S.modello_dichiarato(r"C:\non\esiste\x.itf"), "")


class TestScaricamento(unittest.TestCase):
    """scarica_archivio con una finta risposta HTTP: si prova la logica del
    file provvisorio, dell'annullamento e del progresso, non la rete."""

    class _Risposta(object):
        def __init__(self, dati, lunghezza=True):
            self._dati = dati
            self._letti = 0
            self.headers = {"Content-Length": str(len(dati))} if lunghezza else {}

        def read(self, n):
            pezzo = self._dati[self._letti:self._letti + n]
            self._letti += len(pezzo)
            return pezzo

        def close(self):
            pass

    def _apri(self, dati, lunghezza=True):
        return lambda url, timeout: self._Risposta(dati, lunghezza)

    def test_scarica_e_riporta_il_progresso(self):
        cartella = tempfile.mkdtemp()
        dati = b"z" * 200000
        passi = []
        comune = S.leggi_indice(PAGINA)[0]
        percorso = S.scarica_archivio(comune, cartella,
                                      progresso=lambda f, t: passi.append((f, t)),
                                      apri=self._apri(dati))
        self.assertEqual(os.path.basename(percorso), "5304000101.zip")
        with io.open(percorso, "rb") as f:
            self.assertEqual(f.read(), dati)
        self.assertEqual(passi[-1], (len(dati), len(dati)))

    def test_senza_content_length_il_totale_resta_zero(self):
        cartella = tempfile.mkdtemp()
        passi = []
        S.scarica_archivio(S.leggi_indice(PAGINA)[0], cartella,
                           progresso=lambda f, t: passi.append((f, t)),
                           apri=self._apri(b"x" * 1000, lunghezza=False))
        self.assertEqual(passi[-1][1], 0)

    def test_annullando_non_resta_nessun_file(self):
        cartella = tempfile.mkdtemp()
        with self.assertRaises(S.InterruttoDallUtente):
            S.scarica_archivio(S.leggi_indice(PAGINA)[0], cartella,
                               annullato=lambda: True,
                               apri=self._apri(b"y" * 100000))
        self.assertEqual(os.listdir(cartella), [],
                         "un download interrotto non deve lasciare avanzi")

    def test_un_errore_a_meta_non_lascia_un_file_a_meta(self):
        cartella = tempfile.mkdtemp()

        class Rotta(object):
            headers = {"Content-Length": "100000"}

            def __init__(self):
                self._n = 0

            def read(self, n):
                self._n += 1
                if self._n > 2:
                    raise IOError("connessione caduta")
                return b"k" * n

            def close(self):
                pass

        with self.assertRaises(IOError):
            S.scarica_archivio(S.leggi_indice(PAGINA)[0], cartella,
                               apri=lambda u, t: Rotta())
        self.assertEqual(os.listdir(cartella), [])


if __name__ == "__main__":
    unittest.main(verbosity=2)
