# -*- coding: utf-8 -*-
# Prove del registro dell'archivio.
#
# Gli ITF di prova sono minuscoli ma VERI nella forma: TABL/OBJE/ETAB come li
# scrive l'esportatore, comprese le spaziature irregolari che si vedono nei
# file di consegna (un comune ha il nome incolonnato con spazi, l'altro no).
#
# Eseguire con l'interprete di QGIS o con python puro: questo modulo non
# importa qgis.
import os
import io
import sqlite3
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tidashboard import archivio as A


def _itf(cartella, corpo, nome="prova.itf"):
    percorso = os.path.join(cartella, nome)
    testo = ("SCNT\nINTERLIS Export generated by prova\n////\n"
             "MTID INTERLIS1\nMODL MD01MUTI7MN95\n"
             "TOPI Beni_immobili\n") + corpo + "ETOP\nENDE\n"
    with io.open(percorso, "w", encoding="latin-1", newline="\r\n") as f:
        f.write(testo)
    return percorso


def _tabella(nome, *righe):
    return "TABL %s\n" % nome + "".join(r + "\n" for r in righe) + "ETAB\n"


class TestLetturaItf(unittest.TestCase):
    def test_legge_il_comune_come_lo_scrive_l_esportatore(self):
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune", "OBJE 22140 Lavertezzo 5112 422"))
        c = A.comune_di_itf(p)
        self.assertEqual((c.numero, c.nome, c.bfs), ("422", "Lavertezzo", "5112"))
        self.assertEqual(c.dataset, "422")

    def test_il_nome_incolonnato_con_spazi(self):
        """Forma vera, presa da una consegna: il campo e' riempito di spazi
        fino alla colonna. Tagliare per posizione qui non funziona."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune",
                          "OBJE 1                 Coldrerio                      5251 611"))
        c = A.comune_di_itf(p)
        self.assertEqual((c.numero, c.nome, c.bfs), ("611", "Coldrerio", "5251"))

    def test_un_nome_con_spazi_dentro(self):
        """'Castel San Pietro' e' un comune vero, e spezzando per posizione
        diventerebbe 'Castel' con il resto buttato."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune", "OBJE 7 Castel San Pietro 5249 606"))
        c = A.comune_di_itf(p)
        self.assertEqual(c.nome, "Castel San Pietro")
        self.assertEqual((c.numero, c.bfs), ("606", "5249"))

    def test_le_tabelle_che_SOMIGLIANO_a_Comune_non_contano(self):
        """Nel modello ci sono anche PosComune e SimboloComune: un confronto
        'comune in nome' li prenderebbe, e il primo OBJE di PosComune non ha
        affatto la forma di un comune."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("PosComune", "OBJE 9 999 888")
                 + _tabella("SimboloComune", "OBJE 3 1 2")
                 + _tabella("Comune", "OBJE 22140 Lavertezzo 5112 422"))
        c = A.comune_di_itf(p)
        self.assertEqual(c.nome, "Lavertezzo")

    def test_una_riga_malformata_non_diventa_un_comune(self):
        """Un nome inventato e' peggio di nessun nome: il piano lo
        stamperebbe in intestazione."""
        for riga in ("OBJE 22140 Lavertezzo 5112",       # manca un numero
                     "OBJE 22140 5112 422",              # manca il nome
                     "OBJE 22140 Lavertezzo abc 422",    # bfs non numerico
                     "OBJE"):
            p = _itf(tempfile.mkdtemp(), _tabella("Comune", riga))
            self.assertIsNone(A.comune_di_itf(p), riga)

    def test_due_comuni_in_una_consegna_non_si_riducono_a_uno(self):
        """IL CASO CHE MESCOLEREBBE I DATI: sotto un nome di dataset solo,
        due comuni finirebbero indistinguibili, e il DXF del primo
        conterrebbe anche il secondo. comune_di_itf deve rifiutarsi, e
        leggi_comuni_itf deve farli vedere tutti e due."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune", "OBJE 1 Lavertezzo 5112 422",
                          "OBJE 2 Coldrerio 5251 611"))
        self.assertIsNone(A.comune_di_itf(p))
        tutti = A.leggi_comuni_itf(p)
        self.assertEqual([c.nome for c in tutti], ["Lavertezzo", "Coldrerio"])

    def test_un_itf_senza_tabella_Comune(self):
        p = _itf(tempfile.mkdtemp(), _tabella("Fondo", "OBJE 1 TI42200 12"))
        self.assertEqual(A.leggi_comuni_itf(p), [])
        self.assertIsNone(A.comune_di_itf(p))

    def test_un_file_che_non_c_e(self):
        self.assertEqual(A.leggi_comuni_itf(r"C:\mai\esistito.itf"), [])
        self.assertEqual(A.leggi_comuni_itf(None), [])
        self.assertIsNone(A.comune_di_itf(""))


class TestRegistro(unittest.TestCase):
    def setUp(self):
        self.g = os.path.join(tempfile.mkdtemp(), "archivio.gpkg")
        sqlite3.connect(self.g).close()      # un file sqlite vuoto

    def test_un_archivio_appena_nato_e_vuoto(self):
        """Senza la tabella il registro non deve esplodere: un archivio senza
        comuni e' uno stato normale, non un errore."""
        self.assertEqual(A.registrati(self.g), [])

    def test_annota_e_rilegge(self):
        c = A.Comune("422", "Lavertezzo", "5112")
        self.assertTrue(A.registra(self.g, c, r"C:\dati\5112000101.itf", "2026-08-27"))
        (r,) = A.registrati(self.g)
        self.assertEqual((r["numero"], r["nome"], r["bfs"]), ("422", "Lavertezzo", "5112"))
        self.assertEqual(r["itf"], r"C:\dati\5112000101.itf")
        self.assertEqual(r["importato"], "2026-08-27")

    def test_riannotare_lo_stesso_comune_sovrascrive(self):
        """E' il caso del --replace: l'ITF nuovo sta altrove, e tenere anche
        il percorso vecchio darebbe due righe per un comune solo."""
        c = A.Comune("422", "Lavertezzo", "5112")
        A.registra(self.g, c, r"C:\vecchio\a.itf")
        A.registra(self.g, c, r"C:\nuovo\a.itf")
        righe = A.registrati(self.g)
        self.assertEqual(len(righe), 1)
        self.assertEqual(righe[0]["itf"], r"C:\nuovo\a.itf")

    def test_l_ordine_e_per_numero_non_per_testo(self):
        """Ordinati come testo, il 90 verrebbe dopo il 611."""
        for n in ("611", "90", "422", "5"):
            A.registra(self.g, A.Comune(n, "comune %s" % n), "x.itf")
        self.assertEqual([r["numero"] for r in A.registrati(self.g)],
                         ["5", "90", "422", "611"])

    def test_dimenticare_toglie_dal_registro(self):
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        A.registra(self.g, A.Comune("611", "Coldrerio"), "b.itf")
        self.assertTrue(A.dimentica(self.g, "422"))
        self.assertEqual([r["numero"] for r in A.registrati(self.g)], ["611"])

    def test_registrare_un_comune_che_non_c_e_non_scrive_niente(self):
        self.assertFalse(A.registra(self.g, None, "a.itf"))
        self.assertEqual(A.registrati(self.g), [])


class TestDisallineamento(unittest.TestCase):
    """Le due verita': i dati (T_ILI2DB_DATASET, scritto da ili2gpkg) e il
    nostro registro. Quando divergono bisogna accorgersene, perche' un comune
    presente nei dati ma non a registro non si puo' esportare in DXF."""

    def setUp(self):
        self.g = os.path.join(tempfile.mkdtemp(), "archivio.gpkg")
        con = sqlite3.connect(self.g)
        con.execute("CREATE TABLE T_ILI2DB_DATASET (T_Id INTEGER, datasetname TEXT)")
        con.commit()
        con.close()

    def _dataset(self, *nomi):
        con = sqlite3.connect(self.g)
        for i, n in enumerate(nomi, 1):
            con.execute("INSERT INTO T_ILI2DB_DATASET VALUES (?, ?)", (i, n))
        con.commit()
        con.close()

    def test_un_archivio_coerente_non_segnala_niente(self):
        self._dataset("422", "611")
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        A.registra(self.g, A.Comune("611", "Coldrerio"), "b.itf")
        self.assertEqual(A.disallineati(self.g), ([], []))

    def test_importato_fuori_dal_plugin(self):
        """C'e' nei dati ma non sappiamo da quale ITF: di quel comune non si
        puo' fare il DXF, e va detto invece di scoprirlo al momento."""
        self._dataset("422", "611")
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        self.assertEqual(A.disallineati(self.g), (["611"], []))

    def test_il_registro_promette_un_comune_che_non_c_e(self):
        self._dataset("422")
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        A.registra(self.g, A.Comune("611", "Coldrerio"), "b.itf")
        self.assertEqual(A.disallineati(self.g), ([], ["611"]))

    def test_legge_i_dataset_dichiarati(self):
        self._dataset("422", "611", "422")     # ripetuto: un dataset, piu' righe
        self.assertEqual(A.dataset_nel_gpkg(self.g), ["422", "611"])


class TestPianificazione(unittest.TestCase):
    """La decisione davanti a un ITF e a un archivio. I casi che RIFIUTANO
    contano piu' degli altri: sono quelli che, passando, lascerebbero un
    archivio da cui non si torna indietro."""

    def setUp(self):
        self.d = tempfile.mkdtemp()
        self.g = os.path.join(self.d, "archivio.gpkg")

    def _itf_di(self, *comuni):
        righe = ["OBJE %d %s %s %s" % (i, n, b, nr)
                 for i, (n, b, nr) in enumerate(comuni, 1)]
        return _itf(self.d, _tabella("Comune", *righe),
                    nome="c%d.itf" % len(comuni))

    def _archivio(self, dataset=(), modello="MD01MUTI7MN95", con_colonna=True):
        """Un GeoPackage con quel tanto di ili2gpkg che serve a decidere."""
        con = sqlite3.connect(self.g)
        con.execute("CREATE TABLE T_ILI2DB_MODEL (modelName TEXT)")
        if modello:
            con.execute("INSERT INTO T_ILI2DB_MODEL VALUES (?)", (modello,))
        con.execute("CREATE TABLE T_ILI2DB_DATASET (T_Id INTEGER, datasetname TEXT)")
        for i, n in enumerate(dataset, 1):
            con.execute("INSERT INTO T_ILI2DB_DATASET VALUES (?, ?)", (i, n))
        con.execute("CREATE TABLE gpkg_contents (table_name TEXT, data_type TEXT)")
        colonna = ", T_datasetname TEXT" if con_colonna else ""
        con.execute("CREATE TABLE mu_fondo (T_Id INTEGER, numero TEXT%s)" % colonna)
        con.execute("INSERT INTO gpkg_contents VALUES ('mu_fondo', 'features')")
        con.commit()
        con.close()

    # --- si procede ---

    def test_archivio_che_non_c_e_ancora(self):
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.NUOVO)
        self.assertTrue(p.serve_schema)
        self.assertIn("--createDatasetCol", p.flag_schema)
        self.assertEqual(p.flag_dati, ["--import", "--dataset", "422"])

    def test_un_comune_nuovo_dentro_un_archivio_che_c_e(self):
        self._archivio(dataset=("611",))
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.AGGIUNGI)
        self.assertFalse(p.serve_schema, "lo schema non va rifatto: cancellerebbe")
        self.assertEqual(p.flag_dati, ["--import", "--dataset", "422"])
        self.assertEqual(p.presenti, ["611"])

    def test_un_comune_gia_presente_si_sostituisce(self):
        self._archivio(dataset=("422", "611"))
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.SOSTITUISCI)
        self.assertEqual(p.flag_dati, ["--replace", "--dataset", "422"])

    # --- si rifiuta ---

    def test_un_ITF_con_due_comuni_dentro(self):
        """Passando, i due comuni finirebbero sotto un nome solo e il DXF
        dell'uno conterrebbe l'altro."""
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422"),
                                             ("Coldrerio", "5251", "611")))
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("2 comuni", p.motivo)
        self.assertEqual(p.flag_dati, [])

    def test_un_ITF_che_non_dichiara_il_comune(self):
        vuoto = _itf(self.d, _tabella("Fondo", "OBJE 1 TI42200 12"), nome="v.itf")
        p = A.pianifica(self.g, vuoto)
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("nessun comune", p.motivo)

    def test_un_archivio_SENZA_la_colonna_dataset(self):
        """IL RIFIUTO PIU' IMPORTANTE: un GeoPackage fatto dal plugin vecchio.
        Aggiungendoci un comune, le righe gia' dentro resterebbero senza
        proprietario e nessun filtro potrebbe piu' separarle - un danno che
        non si vede al momento e che non si disfa."""
        self._archivio(dataset=("611",), con_colonna=False)
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("T_datasetname", p.motivo)
        self.assertIn("rifatto", p.motivo)

    def test_uno_schema_vecchio_con_ZERO_comuni_dentro(self):
        """IL BUCO CHE AVEVO LASCIATO IO. Il controllo della colonna era
        legato a "ci sono gia' dei comuni": uno schema del plugin vecchio la
        cui importazione dei dati era fallita ha zero dataset, e il piano
        diceva "aggiungi". I dati sarebbero finiti in tabelle incapaci di
        tenere separati i comuni, e il danno si sarebbe visto solo al comune
        dopo."""
        self._archivio(dataset=(), con_colonna=False)
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("T_datasetname", p.motivo)

    def test_uno_schema_senza_nemmeno_le_tabelle(self):
        """Rifiutare va bene, ma non per il motivo sbagliato: qui la colonna
        non manca, mancano le tabelle. Dire "manca T_datasetname" parlerebbe
        di tabelle che non esistono."""
        con = sqlite3.connect(self.g)
        con.execute("CREATE TABLE T_ILI2DB_MODEL (modelName TEXT)")
        con.execute("INSERT INTO T_ILI2DB_MODEL VALUES ('MD01MUTI7MN95')")
        con.execute("CREATE TABLE gpkg_contents (table_name TEXT, data_type TEXT)")
        con.commit()
        con.close()
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("nessuna tabella", p.motivo)
        self.assertNotIn("T_datasetname", p.motivo)

    def test_un_file_che_non_e_un_GeoPackage(self):
        with io.open(self.g, "w", encoding="ascii") as f:
            f.write("questo non e' un database")
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("SQLite", p.motivo)

    def test_un_GeoPackage_di_qualcun_altro(self):
        """Un GeoPackage vero ma non fatto da ili2gpkg: importarci dentro
        rovinerebbe il file di un altro lavoro."""
        con = sqlite3.connect(self.g)
        con.execute("CREATE TABLE gpkg_contents (table_name TEXT, data_type TEXT)")
        con.commit(); con.close()
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")))
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("ili2gpkg", p.motivo)

    def test_due_modelli_nello_stesso_archivio(self):
        self._archivio(dataset=("611",), modello="MD01MUCH24MN95I")
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")),
                        modello_atteso="MD01MUTI7MN95")
        self.assertEqual(p.azione, A.RIFIUTA)
        self.assertIn("MD01MUCH24MN95I", p.motivo)

    def test_il_modello_giusto_passa(self):
        self._archivio(dataset=("611",), modello="MD01MUTI7MN95")
        p = A.pianifica(self.g, self._itf_di(("Lavertezzo", "5112", "422")),
                        modello_atteso="MD01MUTI7MN95")
        self.assertEqual(p.azione, A.AGGIUNGI)

    def test_ogni_rifiuto_porta_un_motivo(self):
        """Un rifiuto senza motivo e' indistinguibile da un guasto."""
        casi = [A.pianifica("", self._itf_di(("L", "5112", "422"))),
                A.pianifica(self.g, "C:\mai\esistito.itf"),
                A.pianifica(self.g, self._itf_di(("L", "5112", "422"),
                                                 ("C", "5251", "611")))]
        for p in casi:
            self.assertEqual(p.azione, A.RIFIUTA)
            self.assertTrue(p.motivo and len(p.motivo) > 20, repr(p.motivo))


class TestCartella(unittest.TestCase):
    """L'importazione di una cartella intera.

    Serve perche' l'archivio e' cantonale: 106 comuni uno alla volta non li
    carica nessuno. E deve poter RIPRENDERE, non ricominciare: un giro da
    venti minuti che si interrompe a meta' non va rifatto da capo."""

    def setUp(self):
        self.d = tempfile.mkdtemp()
        self.cartella = os.path.join(self.d, "consegne")
        os.makedirs(self.cartella)
        self.g = os.path.join(self.d, "archivio.gpkg")

    def _file(self, nome, *comuni):
        righe = ["OBJE %d %s %s %s" % (i, n, b, nr)
                 for i, (n, b, nr) in enumerate(comuni, 1)]
        return _itf(self.cartella, _tabella("Comune", *righe), nome=nome)

    def _archivio(self, *dataset):
        con = sqlite3.connect(self.g)
        con.execute("CREATE TABLE T_ILI2DB_MODEL (modelName TEXT)")
        con.execute("INSERT INTO T_ILI2DB_MODEL VALUES ('MD01MUTI7MN95')")
        con.execute("CREATE TABLE T_ILI2DB_DATASET (T_Id INTEGER, datasetname TEXT)")
        for i, n in enumerate(dataset, 1):
            con.execute("INSERT INTO T_ILI2DB_DATASET VALUES (?, ?)", (i, n))
        con.execute("CREATE TABLE gpkg_contents (table_name TEXT, data_type TEXT)")
        con.execute("CREATE TABLE mu_fondo (T_Id INTEGER, T_datasetname TEXT)")
        con.execute("INSERT INTO gpkg_contents VALUES ('mu_fondo', 'features')")
        con.commit()
        con.close()

    def test_solo_il_PRIMO_crea_lo_schema(self):
        """IL CASO CHE ROVINEREBBE TUTTO. pianifica() guarda l'archivio com'e'
        adesso: chiamandola per ogni file su un archivio che non esiste
        ancora, tutti e tre direbbero "nuovo" e si rifarebbe lo schema tre
        volte - cioe' si cancellerebbe tutto a ogni giro, lasciando solo
        l'ultimo comune."""
        self._file("a.itf", ("Lavertezzo", "5112", "422"))
        self._file("b.itf", ("Coldrerio", "5251", "611"))
        self._file("c.itf", ("Arzo", "5249", "606"))
        lavori = A.pianifica_cartella(self.g, self.cartella)
        self.assertEqual([l.azione for l in lavori],
                         [A.NUOVO, A.AGGIUNGI, A.AGGIUNGI])

    def test_riprende_invece_di_ricominciare(self):
        """Il giro precedente si era fermato dopo il primo comune."""
        self._file("a.itf", ("Lavertezzo", "5112", "422"))
        self._file("b.itf", ("Coldrerio", "5251", "611"))
        self._archivio("422")
        lavori = A.pianifica_cartella(self.g, self.cartella)
        self.assertEqual([l.azione for l in lavori], [A.GIA_FATTO, A.AGGIUNGI])
        self.assertEqual([l.da_fare for l in lavori], [False, True])

    def test_con_rifai_si_riaggiornano_tutti(self):
        self._file("a.itf", ("Lavertezzo", "5112", "422"))
        self._file("b.itf", ("Coldrerio", "5251", "611"))
        self._archivio("422")
        lavori = A.pianifica_cartella(self.g, self.cartella, rifai=True)
        self.assertEqual([l.azione for l in lavori], [A.SOSTITUISCI, A.AGGIUNGI])

    def test_due_file_per_lo_stesso_comune(self):
        """Quale dei due valga non lo puo' decidere il programma, e lasciare
        vincere l'ultimo letto sarebbe una sovrascrittura silenziosa."""
        self._file("vecchio.itf", ("Lavertezzo", "5112", "422"))
        self._file("nuovo.itf", ("Lavertezzo", "5112", "422"))
        lavori = A.pianifica_cartella(self.g, self.cartella)
        self.assertEqual([l.azione for l in lavori], [A.NUOVO, A.RIFIUTA])
        # A fermarsi e' il SECONDO in ordine alfabetico, e il motivo NOMINA
        # l'altro file: non si sceglie il piu' recente ne' il piu' grande,
        # perche' sarebbe indovinare. Chi guarda deve poter decidere.
        self.assertIn("nuovo.itf", lavori[0].itf)
        self.assertIn("vecchio.itf", lavori[1].itf)
        self.assertIn("nuovo.itf", lavori[1].motivo)

    def test_un_file_guasto_non_ferma_gli_altri(self):
        self._file("a.itf", ("Lavertezzo", "5112", "422"))
        _itf(self.cartella, _tabella("Fondo", "OBJE 1 x 2"), nome="b.itf")
        self._file("c.itf", ("Coldrerio", "5251", "611"))
        lavori = A.pianifica_cartella(self.g, self.cartella)
        self.assertEqual([l.azione for l in lavori],
                         [A.NUOVO, A.RIFIUTA, A.AGGIUNGI])

    def test_l_ordine_non_cambia_fra_un_giro_e_l_altro(self):
        """Senza un ordine stabile, "dove ero arrivato" non si sa."""
        for nome in ("zurigo.itf", "Airolo.itf", "biasca.itf"):
            self._file(nome, ("C" + nome[0], "5000", str(400 + len(nome))))
        a = [os.path.basename(p) for p in A.itf_nella_cartella(self.cartella)]
        b = [os.path.basename(p) for p in A.itf_nella_cartella(self.cartella)]
        self.assertEqual(a, b)
        self.assertEqual(a, ["Airolo.itf", "biasca.itf", "zurigo.itf"])

    def test_una_cartella_senza_itf(self):
        self.assertEqual(A.itf_nella_cartella(self.cartella), [])
        self.assertEqual(A.pianifica_cartella(self.g, self.cartella), [])
        self.assertIn("nessun file", A.riassunto([]))

    def test_una_cartella_che_non_esiste(self):
        self.assertEqual(A.itf_nella_cartella(os.path.join(self.d, "mai")), [])
        self.assertEqual(A.itf_nella_cartella(None), [])

    def test_i_flag_vengono_dal_piano_non_da_una_seconda_regola(self):
        self._file("a.itf", ("Lavertezzo", "5112", "422"))
        self._file("b.itf", ("Coldrerio", "5251", "611"))
        primo, secondo = A.pianifica_cartella(self.g, self.cartella)
        schema, dati = A.flag_di(primo)
        self.assertIn("--createDatasetCol", schema)
        self.assertEqual(dati, ["--import", "--dataset", "422"])
        schema2, dati2 = A.flag_di(secondo)
        self.assertEqual(schema2, [], "lo schema si fa una volta sola")
        self.assertEqual(dati2, ["--import", "--dataset", "611"])

    def test_il_riassunto_conta_tutto(self):
        self._file("a.itf", ("Lavertezzo", "5112", "422"))
        self._file("b.itf", ("Coldrerio", "5251", "611"))
        _itf(self.cartella, _tabella("Fondo", "OBJE 1 x 2"), nome="c.itf")
        self._archivio("422")
        testo = A.riassunto(A.pianifica_cartella(self.g, self.cartella))
        self.assertIn("1 da aggiungere", testo)
        self.assertIn("1 gia' dentro", testo)
        self.assertIn("1 non importabili", testo)


if __name__ == "__main__":
    unittest.main(verbosity=2)
