# -*- coding: utf-8 -*-
# Prove del registro dell'archivio.
#
# Gli ITF di prova sono minuscoli ma VERI nella forma: TABL/OBJE/ETAB come li
# scrive l'esportatore, comprese le spaziature irregolari che si vedono nei
# file di consegna (un comune ha il nome incolonnato con spazi, l'altro no).
#
# Eseguire con l'interprete di QGIS o con python puro: questo modulo non
# importa qgis.
import os
import io
import sqlite3
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tidashboard import archivio as A


def _itf(cartella, corpo, nome="prova.itf"):
    percorso = os.path.join(cartella, nome)
    testo = ("SCNT\nINTERLIS Export generated by prova\n////\n"
             "MTID INTERLIS1\nMODL MD01MUTI7MN95\n"
             "TOPI Beni_immobili\n") + corpo + "ETOP\nENDE\n"
    with io.open(percorso, "w", encoding="latin-1", newline="\r\n") as f:
        f.write(testo)
    return percorso


def _tabella(nome, *righe):
    return "TABL %s\n" % nome + "".join(r + "\n" for r in righe) + "ETAB\n"


class TestLetturaItf(unittest.TestCase):
    def test_legge_il_comune_come_lo_scrive_l_esportatore(self):
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune", "OBJE 22140 Lavertezzo 5112 422"))
        c = A.comune_di_itf(p)
        self.assertEqual((c.numero, c.nome, c.bfs), ("422", "Lavertezzo", "5112"))
        self.assertEqual(c.dataset, "422")

    def test_il_nome_incolonnato_con_spazi(self):
        """Forma vera, presa da una consegna: il campo e' riempito di spazi
        fino alla colonna. Tagliare per posizione qui non funziona."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune",
                          "OBJE 1                 Coldrerio                      5251 611"))
        c = A.comune_di_itf(p)
        self.assertEqual((c.numero, c.nome, c.bfs), ("611", "Coldrerio", "5251"))

    def test_un_nome_con_spazi_dentro(self):
        """'Castel San Pietro' e' un comune vero, e spezzando per posizione
        diventerebbe 'Castel' con il resto buttato."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune", "OBJE 7 Castel San Pietro 5249 606"))
        c = A.comune_di_itf(p)
        self.assertEqual(c.nome, "Castel San Pietro")
        self.assertEqual((c.numero, c.bfs), ("606", "5249"))

    def test_le_tabelle_che_SOMIGLIANO_a_Comune_non_contano(self):
        """Nel modello ci sono anche PosComune e SimboloComune: un confronto
        'comune in nome' li prenderebbe, e il primo OBJE di PosComune non ha
        affatto la forma di un comune."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("PosComune", "OBJE 9 999 888")
                 + _tabella("SimboloComune", "OBJE 3 1 2")
                 + _tabella("Comune", "OBJE 22140 Lavertezzo 5112 422"))
        c = A.comune_di_itf(p)
        self.assertEqual(c.nome, "Lavertezzo")

    def test_una_riga_malformata_non_diventa_un_comune(self):
        """Un nome inventato e' peggio di nessun nome: il piano lo
        stamperebbe in intestazione."""
        for riga in ("OBJE 22140 Lavertezzo 5112",       # manca un numero
                     "OBJE 22140 5112 422",              # manca il nome
                     "OBJE 22140 Lavertezzo abc 422",    # bfs non numerico
                     "OBJE"):
            p = _itf(tempfile.mkdtemp(), _tabella("Comune", riga))
            self.assertIsNone(A.comune_di_itf(p), riga)

    def test_due_comuni_in_una_consegna_non_si_riducono_a_uno(self):
        """IL CASO CHE MESCOLEREBBE I DATI: sotto un nome di dataset solo,
        due comuni finirebbero indistinguibili, e il DXF del primo
        conterrebbe anche il secondo. comune_di_itf deve rifiutarsi, e
        leggi_comuni_itf deve farli vedere tutti e due."""
        p = _itf(tempfile.mkdtemp(),
                 _tabella("Comune", "OBJE 1 Lavertezzo 5112 422",
                          "OBJE 2 Coldrerio 5251 611"))
        self.assertIsNone(A.comune_di_itf(p))
        tutti = A.leggi_comuni_itf(p)
        self.assertEqual([c.nome for c in tutti], ["Lavertezzo", "Coldrerio"])

    def test_un_itf_senza_tabella_Comune(self):
        p = _itf(tempfile.mkdtemp(), _tabella("Fondo", "OBJE 1 TI42200 12"))
        self.assertEqual(A.leggi_comuni_itf(p), [])
        self.assertIsNone(A.comune_di_itf(p))

    def test_un_file_che_non_c_e(self):
        self.assertEqual(A.leggi_comuni_itf(r"C:\mai\esistito.itf"), [])
        self.assertEqual(A.leggi_comuni_itf(None), [])
        self.assertIsNone(A.comune_di_itf(""))


class TestRegistro(unittest.TestCase):
    def setUp(self):
        self.g = os.path.join(tempfile.mkdtemp(), "archivio.gpkg")
        sqlite3.connect(self.g).close()      # un file sqlite vuoto

    def test_un_archivio_appena_nato_e_vuoto(self):
        """Senza la tabella il registro non deve esplodere: un archivio senza
        comuni e' uno stato normale, non un errore."""
        self.assertEqual(A.registrati(self.g), [])

    def test_annota_e_rilegge(self):
        c = A.Comune("422", "Lavertezzo", "5112")
        self.assertTrue(A.registra(self.g, c, r"C:\dati\5112000101.itf", "2026-08-27"))
        (r,) = A.registrati(self.g)
        self.assertEqual((r["numero"], r["nome"], r["bfs"]), ("422", "Lavertezzo", "5112"))
        self.assertEqual(r["itf"], r"C:\dati\5112000101.itf")
        self.assertEqual(r["importato"], "2026-08-27")

    def test_riannotare_lo_stesso_comune_sovrascrive(self):
        """E' il caso del --replace: l'ITF nuovo sta altrove, e tenere anche
        il percorso vecchio darebbe due righe per un comune solo."""
        c = A.Comune("422", "Lavertezzo", "5112")
        A.registra(self.g, c, r"C:\vecchio\a.itf")
        A.registra(self.g, c, r"C:\nuovo\a.itf")
        righe = A.registrati(self.g)
        self.assertEqual(len(righe), 1)
        self.assertEqual(righe[0]["itf"], r"C:\nuovo\a.itf")

    def test_l_ordine_e_per_numero_non_per_testo(self):
        """Ordinati come testo, il 90 verrebbe dopo il 611."""
        for n in ("611", "90", "422", "5"):
            A.registra(self.g, A.Comune(n, "comune %s" % n), "x.itf")
        self.assertEqual([r["numero"] for r in A.registrati(self.g)],
                         ["5", "90", "422", "611"])

    def test_dimenticare_toglie_dal_registro(self):
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        A.registra(self.g, A.Comune("611", "Coldrerio"), "b.itf")
        self.assertTrue(A.dimentica(self.g, "422"))
        self.assertEqual([r["numero"] for r in A.registrati(self.g)], ["611"])

    def test_registrare_un_comune_che_non_c_e_non_scrive_niente(self):
        self.assertFalse(A.registra(self.g, None, "a.itf"))
        self.assertEqual(A.registrati(self.g), [])


class TestDisallineamento(unittest.TestCase):
    """Le due verita': i dati (T_ILI2DB_DATASET, scritto da ili2gpkg) e il
    nostro registro. Quando divergono bisogna accorgersene, perche' un comune
    presente nei dati ma non a registro non si puo' esportare in DXF."""

    def setUp(self):
        self.g = os.path.join(tempfile.mkdtemp(), "archivio.gpkg")
        con = sqlite3.connect(self.g)
        con.execute("CREATE TABLE T_ILI2DB_DATASET (T_Id INTEGER, datasetname TEXT)")
        con.commit()
        con.close()

    def _dataset(self, *nomi):
        con = sqlite3.connect(self.g)
        for i, n in enumerate(nomi, 1):
            con.execute("INSERT INTO T_ILI2DB_DATASET VALUES (?, ?)", (i, n))
        con.commit()
        con.close()

    def test_un_archivio_coerente_non_segnala_niente(self):
        self._dataset("422", "611")
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        A.registra(self.g, A.Comune("611", "Coldrerio"), "b.itf")
        self.assertEqual(A.disallineati(self.g), ([], []))

    def test_importato_fuori_dal_plugin(self):
        """C'e' nei dati ma non sappiamo da quale ITF: di quel comune non si
        puo' fare il DXF, e va detto invece di scoprirlo al momento."""
        self._dataset("422", "611")
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        self.assertEqual(A.disallineati(self.g), (["611"], []))

    def test_il_registro_promette_un_comune_che_non_c_e(self):
        self._dataset("422")
        A.registra(self.g, A.Comune("422", "Lavertezzo"), "a.itf")
        A.registra(self.g, A.Comune("611", "Coldrerio"), "b.itf")
        self.assertEqual(A.disallineati(self.g), ([], ["611"]))

    def test_legge_i_dataset_dichiarati(self):
        self._dataset("422", "611", "422")     # ripetuto: un dataset, piu' righe
        self.assertEqual(A.dataset_nel_gpkg(self.g), ["422", "611"])


if __name__ == "__main__":
    unittest.main(verbosity=2)
