# Test del controllo sul modello dei dati.
#
# Il modello sbagliato e' il difetto piu' silenzioso di tutta la catena: il file
# si apre, si scarica, si copia e sembra a posto, e ci si accorge di averlo solo
# quando ili2gpkg fallisce a meta' parlando di classi mancanti - oppure, peggio,
# quando l'importazione riesce e il progetto esce vuoto perche' nessuno stile
# trova le tabelle che si aspetta.
#
# Eseguire: python test_modello.py
import io
import os
import sqlite3
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tidashboard import modello as M

TESTA = (b"SCNT\r\n"
         b"INTERLIS Export generated by Autodesk Industry Model 19.1.3, 29.07.2026\r\n"
         b"////\r\n"
         b"MTID INTERLIS1\r\n"
         b"MODL %s\r\n"
         b"TOPI Punti_fissiCategoria1\r\n")


def _itf(cartella, nome_modello=b"MD01MUTI7MN95", testa=None):
    percorso = os.path.join(cartella, "prova.itf")
    with io.open(percorso, "wb") as f:
        f.write(testa if testa is not None else TESTA % nome_modello)
    return percorso


def _gpkg(cartella, modelli=("MD01MUTI7MN95",), con_tabella=True):
    percorso = os.path.join(cartella, "prova.gpkg")
    con = sqlite3.connect(percorso)
    if con_tabella:
        con.execute("CREATE TABLE T_ILI2DB_MODEL (filename TEXT, iliversion TEXT, "
                    "modelName TEXT, content TEXT, importDate INTEGER)")
        con.executemany("INSERT INTO T_ILI2DB_MODEL VALUES (?,?,?,?,?)",
                        [("%s.ili" % m, "1.0", m, "", 0) for m in modelli])
    else:
        con.execute("CREATE TABLE gpkg_contents (table_name TEXT)")
    con.commit()
    con.close()
    return percorso


class TestItf(unittest.TestCase):
    def test_il_modello_ticinese_passa(self):
        percorso = _itf(tempfile.mkdtemp())
        self.assertEqual(M.controlla_itf(percorso), (M.OK, "MD01MUTI7MN95"))
        self.assertEqual(M.spiega(*M.controlla_itf(percorso)), "")

    def test_il_modello_federale_viene_riconosciuto_e_nominato(self):
        """geodienste.ch pubblica la stessa MU in MD01MUCH24MN95I: si scarica
        benissimo, e poi non si importa."""
        percorso = _itf(tempfile.mkdtemp(), b"MD01MUCH24MN95I")
        esito, trovato = M.controlla_itf(percorso)
        self.assertEqual(esito, M.DIVERSO)
        self.assertEqual(trovato, "MD01MUCH24MN95I")
        self.assertTrue(M.e_bloccante(esito))
        messaggio = M.spiega(esito, trovato, "il file")
        self.assertIn("MD01MUCH24MN95I", messaggio)
        self.assertIn("MD01MUTI7MN95", messaggio)
        self.assertIn("geodienste", messaggio,
                      "quando riconosce il modello federale deve dire da dove viene")

    def test_un_modello_qualunque_e_diverso_ma_senza_la_nota_su_geodienste(self):
        percorso = _itf(tempfile.mkdtemp(), b"DM01AVSO24LV95")
        esito, trovato = M.controlla_itf(percorso)
        self.assertEqual(esito, M.DIVERSO)
        self.assertNotIn("geodienste", M.spiega(esito, trovato))

    def test_un_xtf_federale_viene_bloccato_non_solo_segnalato(self):
        """Prima il controllo cercava solo la riga MODL dell'INTERLIS 1:
        davanti a un .xtf non la trovava e rispondeva NON_TROVATO, cioe' "non
        posso verificare" - un avviso, non un blocco. Ma quel file non e'
        un'incertezza nostra: e' un formato che questa catena non importa
        affatto. Era un varco nel "controllo a ogni porta"."""
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "consegna.xtf")
        with io.open(percorso, "wb") as f:
            f.write(b'<?xml version="1.0"?><TRANSFER><HEADERSECTION>'
                    b'<MODELS><MODEL NAME="DM01AVCH24LV95D"/></MODELS>'
                    b"</HEADERSECTION>")
        esito, trovato = M.controlla_itf(percorso)
        self.assertEqual(esito, M.DIVERSO)
        self.assertTrue(M.e_bloccante(esito))
        self.assertIn("XTF", trovato)
        self.assertIn("INTERLIS 1", M.spiega(esito, trovato, "il file"))

    def test_un_xtf_rinominato_itf_non_inganna(self):
        """Si guarda il contenuto, non l'estensione."""
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "travestito.itf")
        with io.open(percorso, "wb") as f:
            f.write(b'<?xml version="1.0"?><TRANSFER><HEADERSECTION>'
                    b"</HEADERSECTION>")
        self.assertTrue(M.e_bloccante(M.controlla_itf(percorso)[0]))

    def test_senza_riga_modl_avvisa_ma_non_blocca(self):
        """Un'intestazione insolita e' un dubbio nostro, non una colpa del
        file: bloccare su un dubbio toglie all'utente una decisione sua."""
        percorso = _itf(tempfile.mkdtemp(), testa=b"SCNT\r\nMTID INTERLIS1\r\n")
        esito, trovato = M.controlla_itf(percorso)
        self.assertEqual(esito, M.NON_TROVATO)
        self.assertFalse(M.e_bloccante(esito))
        self.assertIn("non posso verificare", M.spiega(esito, trovato))

    def test_file_inesistente(self):
        esito, _ = M.controlla_itf(os.path.join(tempfile.mkdtemp(), "manca.itf"))
        self.assertEqual(esito, M.NON_LEGGIBILE)
        self.assertFalse(M.e_bloccante(esito))
        self.assertEqual(M.controlla_itf(""), (M.NON_LEGGIBILE, ""))
        self.assertEqual(M.controlla_itf(None), (M.NON_LEGGIBILE, ""))

    def test_non_legge_tutto_il_file(self):
        """Gli ITF veri arrivano a 200 MB: la riga MODL sta in testa e si legge
        solo quella."""
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "grosso.itf")
        with io.open(percorso, "wb") as f:
            f.write(TESTA % b"MD01MUTI7MN95")
            f.write(b"x" * (2 * 1024 * 1024))
            f.write(b"\r\nMODL QUESTO_NON_DEVE_CONTARE\r\n")
        self.assertEqual(M.modello_di_itf(percorso), "MD01MUTI7MN95")


class TestGpkg(unittest.TestCase):
    def test_legge_il_modello_registrato_da_ili2gpkg(self):
        percorso = _gpkg(tempfile.mkdtemp())
        self.assertEqual(M.controlla_gpkg(percorso), (M.OK, "MD01MUTI7MN95"))

    def test_modello_diverso(self):
        percorso = _gpkg(tempfile.mkdtemp(), modelli=("MD01MUCH24MN95I",))
        esito, trovato = M.controlla_gpkg(percorso)
        self.assertEqual(esito, M.DIVERSO)
        self.assertEqual(trovato, "MD01MUCH24MN95I")

    def test_piu_modelli_basta_che_ci_sia_il_nostro(self):
        """Un GeoPackage puo' portare piu' di un modello importato: la presenza
        di altri non toglie nulla, l'assenza del nostro si'."""
        percorso = _gpkg(tempfile.mkdtemp(),
                         modelli=("CHBase_LV95", "MD01MUTI7MN95"))
        self.assertEqual(M.controlla_gpkg(percorso)[0], M.OK)

    def test_geopackage_non_fatto_da_ili2gpkg(self):
        percorso = _gpkg(tempfile.mkdtemp(), con_tabella=False)
        esito, _ = M.controlla_gpkg(percorso)
        self.assertEqual(esito, M.NON_TROVATO)
        self.assertFalse(M.e_bloccante(esito))

    def test_file_che_non_e_un_database(self):
        cartella = tempfile.mkdtemp()
        percorso = os.path.join(cartella, "finto.gpkg")
        with io.open(percorso, "wb") as f:
            f.write(b"non sono un database")
        self.assertEqual(M.modelli_di_gpkg(percorso), [])

    def test_apre_in_sola_lettura(self):
        """Aprire in scrittura un GeoPackage che QGIS sta gia' usando lo
        bloccherebbe: si verifica che il file non venga toccato."""
        percorso = _gpkg(tempfile.mkdtemp())
        prima = os.stat(percorso).st_mtime_ns
        M.controlla_gpkg(percorso)
        self.assertEqual(os.stat(percorso).st_mtime_ns, prima)

    def test_file_inesistente(self):
        self.assertEqual(M.controlla_gpkg("")[0], M.NON_LEGGIBILE)
        self.assertEqual(M.modelli_di_gpkg("C:\\non\\esiste.gpkg"), [])


class TestCoerenzaConLoScaricamento(unittest.TestCase):
    """scarica_mu non deve avere una sua idea di quale sia il modello giusto:
    due copie della stessa costante prima o poi divergono."""

    def test_una_costante_sola(self):
        from tidashboard import scarica_mu as S
        self.assertIs(S.MODELLO_ATTESO, M.MODELLO_ATTESO)

    def test_una_lettura_sola(self):
        from tidashboard import scarica_mu as S
        percorso = _itf(tempfile.mkdtemp())
        self.assertEqual(S.modello_dichiarato(percorso), M.modello_di_itf(percorso))


if __name__ == "__main__":
    unittest.main(verbosity=2)
